// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type StageType int32

const (
	StageType_STAGE_TYPE_UNSPECIFIED StageType = 0
	StageType_STAGE_TYPE_MAP         StageType = 1
	StageType_STAGE_TYPE_REDUCE      StageType = 2
)

// Enum value maps for StageType.
var (
	StageType_name = map[int32]string{
		0: "STAGE_TYPE_UNSPECIFIED",
		1: "STAGE_TYPE_MAP",
		2: "STAGE_TYPE_REDUCE",
	}
	StageType_value = map[string]int32{
		"STAGE_TYPE_UNSPECIFIED": 0,
		"STAGE_TYPE_MAP":         1,
		"STAGE_TYPE_REDUCE":      2,
	}
)

func (x StageType) Enum() *StageType {
	p := new(StageType)
	*p = x
	return p
}

func (x StageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[1].Descriptor()
}

func (StageType) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[1]
}

func (x StageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageType.Descriptor instead.
func (StageType) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ControlPort   int32                  `protobuf:"varint,3,opt,name=control_port,json=controlPort,proto3" json:"control_port,omitempty"`
	FlightPort    int32                  `protobuf:"varint,4,opt,name=flight_port,json=flightPort,proto3" json:"flight_port,omitempty"`
	NumCores      int32                  `protobuf:"varint,5,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	TotalMemoryMb int64                  `protobuf:"varint,6,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterWorkerRequest) GetControlPort() int32 {
	if x != nil {
		return x.ControlPort
	}
	return 0
}

func (x *RegisterWorkerRequest) GetFlightPort() int32 {
	if x != nil {
		return x.FlightPort
	}
	return 0
}

func (x *RegisterWorkerRequest) GetNumCores() int32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *RegisterWorkerRequest) GetTotalMemoryMb() int64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsagePct   float32                `protobuf:"fixed32,2,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	MemoryUsedMb  int64                  `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,4,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsagePct() float32 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PartitionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	FlightAddress string                 `protobuf:"bytes,3,opt,name=flight_address,json=flightAddress,proto3" json:"flight_address,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // Size in bytes of the partition for Adaptive Query Execution (AQE)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetadata.ProtoReflect.Descriptor instead.
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *PartitionMetadata) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionMetadata) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PartitionMetadata) GetFlightAddress() string {
	if x != nil {
		return x.FlightAddress
	}
	return ""
}

func (x *PartitionMetadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PartitionMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ColumnStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnName    string                 `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	Cardinality   int64                  `protobuf:"varint,2,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	NullCount     int64                  `protobuf:"varint,3,opt,name=null_count,json=nullCount,proto3" json:"null_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnStats) Reset() {
	*x = ColumnStats{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnStats) ProtoMessage() {}

func (x *ColumnStats) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnStats.ProtoReflect.Descriptor instead.
func (*ColumnStats) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *ColumnStats) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *ColumnStats) GetCardinality() int64 {
	if x != nil {
		return x.Cardinality
	}
	return 0
}

func (x *ColumnStats) GetNullCount() int64 {
	if x != nil {
		return x.NullCount
	}
	return 0
}

type TableStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowCount      int64                  `protobuf:"varint,1,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ColStats      []*ColumnStats         `protobuf:"bytes,3,rep,name=col_stats,json=colStats,proto3" json:"col_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableStats) Reset() {
	*x = TableStats{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableStats) ProtoMessage() {}

func (x *TableStats) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableStats.ProtoReflect.Descriptor instead.
func (*TableStats) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *TableStats) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *TableStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *TableStats) GetColStats() []*ColumnStats {
	if x != nil {
		return x.ColStats
	}
	return nil
}

type TaskStatusUpdateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StageId            string                 `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	WorkerId           string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status             TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=control.TaskStatus" json:"status,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProducedPartitions []*PartitionMetadata   `protobuf:"bytes,6,rep,name=produced_partitions,json=producedPartitions,proto3" json:"produced_partitions,omitempty"`
	TableStats         *TableStats            `protobuf:"bytes,7,opt,name=table_stats,json=tableStats,proto3" json:"table_stats,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskStatusUpdateRequest) Reset() {
	*x = TaskStatusUpdateRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdateRequest) ProtoMessage() {}

func (x *TaskStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *TaskStatusUpdateRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdateRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *TaskStatusUpdateRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskStatusUpdateRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdateRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskStatusUpdateRequest) GetProducedPartitions() []*PartitionMetadata {
	if x != nil {
		return x.ProducedPartitions
	}
	return nil
}

func (x *TaskStatusUpdateRequest) GetTableStats() *TableStats {
	if x != nil {
		return x.TableStats
	}
	return nil
}

type TaskStatusUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdateResponse) Reset() {
	*x = TaskStatusUpdateResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdateResponse) ProtoMessage() {}

func (x *TaskStatusUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdateResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdateResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *TaskStatusUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ShuffleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	FlightAddress string                 `protobuf:"bytes,3,opt,name=flight_address,json=flightAddress,proto3" json:"flight_address,omitempty"`
	MapperTaskId  string                 `protobuf:"bytes,4,opt,name=mapper_task_id,json=mapperTaskId,proto3" json:"mapper_task_id,omitempty"`
	PartitionIds  []int32                `protobuf:"varint,5,rep,packed,name=partition_ids,json=partitionIds,proto3" json:"partition_ids,omitempty"` // Support pulling multiple coalesced partitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleInput) Reset() {
	*x = ShuffleInput{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleInput) ProtoMessage() {}

func (x *ShuffleInput) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleInput.ProtoReflect.Descriptor instead.
func (*ShuffleInput) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *ShuffleInput) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ShuffleInput) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ShuffleInput) GetFlightAddress() string {
	if x != nil {
		return x.FlightAddress
	}
	return ""
}

func (x *ShuffleInput) GetMapperTaskId() string {
	if x != nil {
		return x.MapperTaskId
	}
	return ""
}

func (x *ShuffleInput) GetPartitionIds() []int32 {
	if x != nil {
		return x.PartitionIds
	}
	return nil
}

type SubmitTaskRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TaskId    string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StageId   string                 `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	StageType StageType              `protobuf:"varint,3,opt,name=stage_type,json=stageType,proto3,enum=control.StageType" json:"stage_type,omitempty"`
	// Config for MAP stage
	InputFiles []string `protobuf:"bytes,4,rep,name=input_files,json=inputFiles,proto3" json:"input_files,omitempty"`
	MapSql     string   `protobuf:"bytes,5,opt,name=map_sql,json=mapSql,proto3" json:"map_sql,omitempty"`
	// Config for REDUCE stage
	ReduceSql         string          `protobuf:"bytes,6,opt,name=reduce_sql,json=reduceSql,proto3" json:"reduce_sql,omitempty"`
	OutputPartitionId int32           `protobuf:"varint,7,opt,name=output_partition_id,json=outputPartitionId,proto3" json:"output_partition_id,omitempty"`
	ShuffleInputs     []*ShuffleInput `protobuf:"bytes,8,rep,name=shuffle_inputs,json=shuffleInputs,proto3" json:"shuffle_inputs,omitempty"`
	// General parameters
	NumPartitions int32  `protobuf:"varint,9,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	OutputDir     string `protobuf:"bytes,10,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	// AQE & Broadcast Join configuration
	CoalescedPartitions []int32  `protobuf:"varint,11,rep,packed,name=coalesced_partitions,json=coalescedPartitions,proto3" json:"coalesced_partitions,omitempty"`
	BroadcastFiles      []string `protobuf:"bytes,12,rep,name=broadcast_files,json=broadcastFiles,proto3" json:"broadcast_files,omitempty"`
	BroadcastTableNames []string `protobuf:"bytes,13,rep,name=broadcast_table_names,json=broadcastTableNames,proto3" json:"broadcast_table_names,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *SubmitTaskRequest) GetStageType() StageType {
	if x != nil {
		return x.StageType
	}
	return StageType_STAGE_TYPE_UNSPECIFIED
}

func (x *SubmitTaskRequest) GetInputFiles() []string {
	if x != nil {
		return x.InputFiles
	}
	return nil
}

func (x *SubmitTaskRequest) GetMapSql() string {
	if x != nil {
		return x.MapSql
	}
	return ""
}

func (x *SubmitTaskRequest) GetReduceSql() string {
	if x != nil {
		return x.ReduceSql
	}
	return ""
}

func (x *SubmitTaskRequest) GetOutputPartitionId() int32 {
	if x != nil {
		return x.OutputPartitionId
	}
	return 0
}

func (x *SubmitTaskRequest) GetShuffleInputs() []*ShuffleInput {
	if x != nil {
		return x.ShuffleInputs
	}
	return nil
}

func (x *SubmitTaskRequest) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *SubmitTaskRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *SubmitTaskRequest) GetCoalescedPartitions() []int32 {
	if x != nil {
		return x.CoalescedPartitions
	}
	return nil
}

func (x *SubmitTaskRequest) GetBroadcastFiles() []string {
	if x != nil {
		return x.BroadcastFiles
	}
	return nil
}

func (x *SubmitTaskRequest) GetBroadcastTableNames() []string {
	if x != nil {
		return x.BroadcastTableNames
	}
	return nil
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\"\xd1\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12!\n" +
	"\fcontrol_port\x18\x03 \x01(\x05R\vcontrolPort\x12\x1f\n" +
	"\vflight_port\x18\x04 \x01(\x05R\n" +
	"flightPort\x12\x1b\n" +
	"\tnum_cores\x18\x05 \x01(\x05R\bnumCores\x12&\n" +
	"\x0ftotal_memory_mb\x18\x06 \x01(\x03R\rtotalMemoryMb\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\"\n" +
	"\rcpu_usage_pct\x18\x02 \x01(\x02R\vcpuUsagePct\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x03R\fmemoryUsedMb\x12!\n" +
	"\factive_tasks\x18\x04 \x01(\x05R\vactiveTasks\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x01\n" +
	"\x11PartitionMetadata\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12%\n" +
	"\x0eflight_address\x18\x03 \x01(\tR\rflightAddress\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\"o\n" +
	"\vColumnStats\x12\x1f\n" +
	"\vcolumn_name\x18\x01 \x01(\tR\n" +
	"columnName\x12 \n" +
	"\vcardinality\x18\x02 \x01(\x03R\vcardinality\x12\x1d\n" +
	"\n" +
	"null_count\x18\x03 \x01(\x03R\tnullCount\"{\n" +
	"\n" +
	"TableStats\x12\x1b\n" +
	"\trow_count\x18\x01 \x01(\x03R\browCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x121\n" +
	"\tcol_stats\x18\x03 \x03(\v2\x14.control.ColumnStatsR\bcolStats\"\xbf\x02\n" +
	"\x17TaskStatusUpdateRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\tR\astageId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.control.TaskStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12K\n" +
	"\x13produced_partitions\x18\x06 \x03(\v2\x1a.control.PartitionMetadataR\x12producedPartitions\x124\n" +
	"\vtable_stats\x18\a \x01(\v2\x13.control.TableStatsR\n" +
	"tableStats\"4\n" +
	"\x18TaskStatusUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc0\x01\n" +
	"\fShuffleInput\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12%\n" +
	"\x0eflight_address\x18\x03 \x01(\tR\rflightAddress\x12$\n" +
	"\x0emapper_task_id\x18\x04 \x01(\tR\fmapperTaskId\x12#\n" +
	"\rpartition_ids\x18\x05 \x03(\x05R\fpartitionIds\"\x97\x04\n" +
	"\x11SubmitTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\tR\astageId\x121\n" +
	"\n" +
	"stage_type\x18\x03 \x01(\x0e2\x12.control.StageTypeR\tstageType\x12\x1f\n" +
	"\vinput_files\x18\x04 \x03(\tR\n" +
	"inputFiles\x12\x17\n" +
	"\amap_sql\x18\x05 \x01(\tR\x06mapSql\x12\x1d\n" +
	"\n" +
	"reduce_sql\x18\x06 \x01(\tR\treduceSql\x12.\n" +
	"\x13output_partition_id\x18\a \x01(\x05R\x11outputPartitionId\x12<\n" +
	"\x0eshuffle_inputs\x18\b \x03(\v2\x15.control.ShuffleInputR\rshuffleInputs\x12%\n" +
	"\x0enum_partitions\x18\t \x01(\x05R\rnumPartitions\x12\x1d\n" +
	"\n" +
	"output_dir\x18\n" +
	" \x01(\tR\toutputDir\x121\n" +
	"\x14coalesced_partitions\x18\v \x03(\x05R\x13coalescedPartitions\x12'\n" +
	"\x0fbroadcast_files\x18\f \x03(\tR\x0ebroadcastFiles\x122\n" +
	"\x15broadcast_table_names\x18\r \x03(\tR\x13broadcastTableNames\"H\n" +
	"\x12SubmitTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8e\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04*R\n" +
	"\tStageType\x12\x1a\n" +
	"\x16STAGE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTAGE_TYPE_MAP\x10\x01\x12\x15\n" +
	"\x11STAGE_TYPE_REDUCE\x10\x022\xfe\x01\n" +
	"\fControlPlane\x12Q\n" +
	"\x0eRegisterWorker\x12\x1e.control.RegisterWorkerRequest\x1a\x1f.control.RegisterWorkerResponse\x12B\n" +
	"\tHeartbeat\x12\x19.control.HeartbeatRequest\x1a\x1a.control.HeartbeatResponse\x12W\n" +
	"\x10UpdateTaskStatus\x12 .control.TaskStatusUpdateRequest\x1a!.control.TaskStatusUpdateResponse2\x9d\x01\n" +
	"\rWorkerControl\x12E\n" +
	"\n" +
	"SubmitTask\x12\x1a.control.SubmitTaskRequest\x1a\x1b.control.SubmitTaskResponse\x12E\n" +
	"\n" +
	"CancelTask\x12\x1a.control.CancelTaskRequest\x1a\x1b.control.CancelTaskResponseB\x1fZ\x1dcontrol-plane/pkg/proto;protob\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_control_proto_goTypes = []any{
	(TaskStatus)(0),                  // 0: control.TaskStatus
	(StageType)(0),                   // 1: control.StageType
	(*RegisterWorkerRequest)(nil),    // 2: control.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),   // 3: control.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),         // 4: control.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 5: control.HeartbeatResponse
	(*PartitionMetadata)(nil),        // 6: control.PartitionMetadata
	(*ColumnStats)(nil),              // 7: control.ColumnStats
	(*TableStats)(nil),               // 8: control.TableStats
	(*TaskStatusUpdateRequest)(nil),  // 9: control.TaskStatusUpdateRequest
	(*TaskStatusUpdateResponse)(nil), // 10: control.TaskStatusUpdateResponse
	(*ShuffleInput)(nil),             // 11: control.ShuffleInput
	(*SubmitTaskRequest)(nil),        // 12: control.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),       // 13: control.SubmitTaskResponse
	(*CancelTaskRequest)(nil),        // 14: control.CancelTaskRequest
	(*CancelTaskResponse)(nil),       // 15: control.CancelTaskResponse
}
var file_control_proto_depIdxs = []int32{
	7,  // 0: control.TableStats.col_stats:type_name -> control.ColumnStats
	0,  // 1: control.TaskStatusUpdateRequest.status:type_name -> control.TaskStatus
	6,  // 2: control.TaskStatusUpdateRequest.produced_partitions:type_name -> control.PartitionMetadata
	8,  // 3: control.TaskStatusUpdateRequest.table_stats:type_name -> control.TableStats
	1,  // 4: control.SubmitTaskRequest.stage_type:type_name -> control.StageType
	11, // 5: control.SubmitTaskRequest.shuffle_inputs:type_name -> control.ShuffleInput
	2,  // 6: control.ControlPlane.RegisterWorker:input_type -> control.RegisterWorkerRequest
	4,  // 7: control.ControlPlane.Heartbeat:input_type -> control.HeartbeatRequest
	9,  // 8: control.ControlPlane.UpdateTaskStatus:input_type -> control.TaskStatusUpdateRequest
	12, // 9: control.WorkerControl.SubmitTask:input_type -> control.SubmitTaskRequest
	14, // 10: control.WorkerControl.CancelTask:input_type -> control.CancelTaskRequest
	3,  // 11: control.ControlPlane.RegisterWorker:output_type -> control.RegisterWorkerResponse
	5,  // 12: control.ControlPlane.Heartbeat:output_type -> control.HeartbeatResponse
	10, // 13: control.ControlPlane.UpdateTaskStatus:output_type -> control.TaskStatusUpdateResponse
	13, // 14: control.WorkerControl.SubmitTask:output_type -> control.SubmitTaskResponse
	15, // 15: control.WorkerControl.CancelTask:output_type -> control.CancelTaskResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
